import type { Product, Category } from './types';
import { PlaceHolderImages } from './placeholder-images';

const getImage = (id: string) => {
  const image = PlaceHolderImages.find(img => img.id === id);
  return image ? { url: image.imageUrl, hint: image.imageHint } : { url: 'https://picsum.photos/seed/placeholder/600/600', hint: 'placeholder' };
}

export const categories: Category[] = [
  { id: 'sneakers', name: 'Sneakers', parentId: null, imageUrl: getImage('jordan-1').url, imageHint: getImage('jordan-1').hint },
  { id: 'mens-shoes', name: 'Men\'s Shoes', parentId: null, imageUrl: getImage('lacoste-1').url, imageHint: getImage('lacoste-1').hint },
  { id: 'ladies-shoes', name: 'Ladies\' Shoes', parentId: null, imageUrl: getImage('tommy-boots-1').url, imageHint: getImage('tommy-boots-1').hint },
  { id: 'kids-shoes', name: 'Kids\' Shoes', parentId: null, imageUrl: getImage('kids-sneaker-1').url, imageHint: getImage('kids-sneaker-1').hint },
  { id: 'formal-shoes', name: 'Formal Shoes', parentId: 'mens-shoes', imageUrl: getImage('lacoste-1').url, imageHint: getImage('lacoste-1').hint },
  { id: 'ladies-boots', name: 'Boots', parentId: 'ladies-shoes', imageUrl: getImage('tommy-boots-1').url, imageHint: getImage('tommy-boots-1').hint },
  { id: 'soccer-boots', name: 'Soccer Boots', parentId: 'mens-shoes', imageUrl: getImage('soccer-boot-1').url, imageHint: getImage('soccer-boot-1').hint },
];

export const products: Product[] = [
    {
        id: 'samoa-new',
        name: 'Samoa',
        price: 2799,
        images: [
            getImage('samoa-new-1'),
            getImage('samoa-new-2'),
        ],
        description: 'The Samoa is a classic trainer loved for its sleek silhouette and iconic toe bumper. A versatile choice for any casual look, offering timeless style and exceptional comfort.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['Multi-color'],
    },
    {
        id: 'kids-open',
        name: 'Kids open',
        price: 1499,
        images: [
            getImage('kids-open-1'),
            getImage('kids-open-2'),
            getImage('kids-open-3'),
            getImage('kids-open-4'),
        ],
        description: 'Comfortable and stylish open shoes for kids, perfect for warm weather and casual outings. Designed for durability and ease of wear.',
        category: 'kids-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36'],
        colors: ['Multi-color'],
    },
    {
        id: 'kids-sneakers-v5',
        name: 'Kids Sneakers',
        price: 1799,
        images: [
            getImage('kids-sneaker-v4-1'),
            getImage('kids-sneaker-v4-2'),
            getImage('kids-sneaker-v4-3'),
            getImage('kids-sneaker-v4-4'),
            getImage('kids-sneaker-v5-5'),
        ],
        description: 'Perfect for the little ones, these stylish kids sneakers are designed for comfort and durability. Ideal for toddlers and early walkers.',
        category: 'kids-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30'],
        colors: ['Multi-color'],
    },
    {
        id: 'kids-sneakers-v4',
        name: 'Kids Sneakers',
        price: 1799,
        images: [
            getImage('kids-sneaker-v4-1'),
            getImage('kids-sneaker-v4-2'),
            getImage('kids-sneaker-v4-3'),
            getImage('kids-sneaker-v4-4'),
        ],
        description: 'Durable and stylish sneakers for active kids. Perfect for school and play, offering great support and comfort.',
        category: 'kids-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37'],
        colors: ['Multi-color'],
    },
    {
        id: 'asics-gel-sneakers',
        name: 'ASICS GEL sneakers',
        price: 2999,
        images: [
            getImage('asics-gel-1'),
            getImage('asics-gel-2'),
        ],
        description: 'The ASICS GEL sneakers offer superior cushioning and stability for all-day comfort. Featuring GEL technology for impact absorption and a sleek design that works for both active and casual wear.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['36', '37', '38', '39', '40', '41'],
        colors: ['Multi-color'],
    },
    {
        id: 'jordan-voodoo',
        name: 'Jordan Voodoo',
        price: 3499,
        images: [
            getImage('jordan-voodoo-1'),
            getImage('jordan-voodoo-2'),
        ],
        description: 'The Jordan Voodoo features a unique, patchwork-inspired design with premium materials and distinctive details. A standout addition to any sneaker collection, offering both iconic style and exceptional comfort.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['36', '37', '38', '39', '40', '41', '42', '43', '44', '45'],
        colors: ['Multi-color'],
    },
    {
        id: 'bape-star',
        name: 'Bape star',
        price: 2999,
        images: [
            getImage('bape-star-1'),
            getImage('bape-star-2'),
            getImage('bape-star-3'),
        ],
        description: 'Iconic Bape Star sneakers featuring a bold design and signature star logo. Crafted with premium materials for a distinct street-style look and lasting comfort.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44'],
        colors: ['Multi-color'],
    },
    {
        id: 'nike-ld-waffle',
        name: 'Nike LD waffle',
        price: 3499,
        images: [
            getImage('nike-ld-waffle-1'),
        ],
        description: 'The Nike LD Waffle is a fusion of two iconic Nike silhouettes: the LDV and the Waffle Daybreak. Featuring a unique doubled-up aesthetic with overlapping tongues, Swooshes, and laces, it offers a distinct, high-fashion look combined with classic waffle traction and comfort.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['Multi-color'],
    },
    {
        id: 'nb-9060',
        name: 'New Balance 9060',
        price: 3499,
        images: [
            getImage('nb-9060-3'),
            getImage('nb-9060-4'),
        ],
        description: 'The New Balance 9060 is a new expression of refined style and innovation-led design. It reinterprets familiar elements from classic 99X models with a warped sensibility inspired by the proudly futuristic, visible tech aesthetic of the Y2K era.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['38', '39', '40', '41', '42', '43', '44', '45'],
        colors: ['Multi-color'],
    },
    {
        id: 'asics-sneakers',
        name: 'Asics',
        price: 3499,
        images: [
            getImage('asics-1'),
            getImage('asics-2'),
            getImage('asics-3'),
            getImage('asics-4'),
            getImage('asics-5'),
        ],
        description: 'High-performance Asics sneakers designed for comfort and durability. Perfect for running or casual wear with a sleek, modern aesthetic.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['36', '37', '38', '39', '40'],
        colors: ['Multi-color'],
    },
    {
        id: 'men-sandals',
        name: 'Men sandals',
        price: 1800,
        images: [
            getImage('men-sandals-1'),
            getImage('men-sandals-2'),
            getImage('men-sandals-3'),
        ],
        description: 'Stylish and comfortable men\'s sandals, perfect for warm weather or casual wear. Crafted for durability and a relaxed fit.',
        category: 'mens-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['Black', 'Brown'],
    },
    {
        id: 'soccer-boots-pro',
        name: 'Soccer boots',
        price: 3999,
        images: [
            getImage('soccer-boot-1'),
            getImage('soccer-boot-2'),
            getImage('soccer-boot-3'),
            getImage('soccer-boot-4'),
            getImage('soccer-boot-5'),
            getImage('soccer-boot-6'),
        ],
        description: 'Take your game to the next level with these high-performance soccer boots. Engineered for maximum traction and precision control, they offer a comfortable fit and durable construction for any surface.',
        category: 'mens-shoes',
        subcategory: 'soccer-boots',
        relatedProducts: [],
        sizes: ['38', '39', '40', '41', '42', '43', '44', '45'],
        colors: ['Multi-color'],
    },
    {
        id: 'clarks-official',
        name: 'Clarks',
        price: 2999,
        images: [
            getImage('clarks-1'),
            getImage('clarks-2'),
            getImage('clarks-3'),
            getImage('clarks-4'),
        ],
        description: 'Timeless comfort and classic style with Clarks. Crafted with premium materials for a refined look and exceptional durability, these shoes are perfect for both formal and smart-casual settings.',
        category: 'mens-shoes',
        subcategory: 'formal-shoes',
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44'],
        colors: ['Brown', 'Black'],
    },
    {
        id: 'nike-shox-new',
        name: 'Nike shocks',
        price: 3999,
        images: [
            getImage('nike-shox-new-1'),
            getImage('nike-shox-new-2'),
            getImage('nike-shox-new-3'),
            getImage('nike-shox-new-4'),
        ],
        description: 'Experience responsive cushioning and iconic style with the Nike Shox. Designed for impact protection and a bold look, these sneakers feature the legendary Shox columns for a springy feel with every step.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['Black/Grey'],
    },
    {
        id: 'polo-loafer-new',
        name: 'Polo loafer',
        price: 2499,
        images: [
            getImage('polo-loafer-1'),
        ],
        description: 'Sophisticated and comfortable, the Polo Loafer is a timeless choice for a refined look. Crafted with attention to detail, these loafers offer effortless style and all-day comfort for any formal or smart-casual occasion.',
        category: 'mens-shoes',
        subcategory: 'formal-shoes',
        relatedProducts: [],
        sizes: ['39', '40', '41', '42', '43', '44', '45'],
        colors: ['Black', 'Brown'],
    },
    {
        id: 'samba-double-sole',
        name: 'Samba double sole',
        price: 2999,
        images: [
            getImage('samba-double-sole-1'),
            getImage('samba-double-sole-2'),
        ],
        description: 'Elevate your style with the Samba Double Sole. This fresh take on the classic silhouette features a bold platform sole, offering a modern aesthetic while maintaining the iconic Samba heritage and comfort.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['36', '37', '38', '39', '40', '41', '42', '43', '44', '45'],
        colors: ['Black/White'],
    },
    {
        id: 'alexander-mcqueen',
        name: 'Alexander McQueen',
        price: 3499,
        images: [
            getImage('mcqueen-1'),
            getImage('mcqueen-2'),
            getImage('mcqueen-3'),
            getImage('mcqueen-4'),
        ],
        description: 'Iconic oversized sneakers from Alexander McQueen. Combining luxury materials with a bold, contemporary silhouette, these sneakers are perfect for a fashion-forward street style.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['36', '37', '38', '39', '40', '41', '42', '43', '44', '45'],
        colors: ['White', 'Black'],
    },
    {
        id: 'timberland-casual',
        name: 'Casual Timberland',
        price: 2800,
        images: [
            getImage('timberland-casual-new-1'),
            getImage('timberland-casual-new-2'),
            getImage('timberland-casual-new-3'),
        ],
        description: 'A stylish and durable casual shoe from Timberland, perfect for everyday wear, combining ruggedness with a refined aesthetic. Crafted with high-quality materials for long-lasting comfort.',
        category: 'mens-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['Wheat', 'Black', 'Brown'],
    },
    {
        id: 'naked-wolf',
        name: 'Naked wolf',
        price: 3499,
        images: [
            getImage('naked-wolf-1'),
            getImage('naked-wolf-2'),
            getImage('naked-wolf-3'),
            getImage('naked-wolf-4'),
        ],
        description: 'The Naked Wolf sneakers redefine modern luxury footwear with their iconic chunky silhouette and bold aesthetic. Crafted for those who dare to be different, these sneakers combine high-fashion design with exceptional comfort.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['36', '37', '38', '39', '40', '41', '42', '43', '44', '45'],
        colors: ['Black', 'White', 'Beige'],
    },
    {
        id: 'vans-classic',
        name: 'Vans',
        price: 1499,
        images: [
            getImage('vans-1'),
            getImage('vans-2'),
            getImage('vans-3'),
            getImage('vans-4'),
            getImage('vans-5'),
            getImage('vans-6'),
            getImage('vans-7'),
            getImage('vans-8'),
        ],
        description: 'Classic Vans sneakers, perfect for everyday casual wear. Features a timeless design and durable construction.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['37', '38', '39', '40', '41', '42', '43', '44', '45'],
        colors: ['Black', 'White', 'Blue'],
    },
    {
        id: 'new-amiri',
        name: 'New Amiri',
        price: 3499,
        images: [
            getImage('amiri-1'),
            getImage('amiri-2'),
        ],
        description: 'Experience luxury and style with the New Amiri sneakers. Crafted with premium materials and a signature design, these sneakers offer a modern aesthetic and exceptional comfort for those who appreciate high-end fashion.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['38', '39', '40', '41', '42', '43', '44', '45'],
        colors: ['Black', 'White'],
    },
    {
        id: 'nb-550',
        name: 'New balance 550',
        price: 3499,
        images: [
            getImage('nb-550-1'),
            getImage('nb-550-2'),
        ],
        description: 'The New Balance 550 brings retro court style to the modern day. Its clean silhouette and premium materials offer a timeless look and exceptional comfort for everyday wear.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['38', '39', '40', '41', '42', '43', '44', '45'],
        colors: ['White/Grey', 'White/Blue'],
    },
    {
        id: 'mens-boots-new',
        name: 'Men\'s Boots',
        price: 4800,
        images: [
            getImage('mens-boots-1'),
            getImage('mens-boots-2'),
            getImage('mens-boots-3'),
            getImage('mens-boots-4'),
            getImage('mens-boots-5'),
            getImage('mens-boots-6'),
            getImage('mens-boots-7'),
            getImage('mens-boots-8'),
            getImage('mens-boots-9'),
            getImage('mens-boots-10'),
            getImage('mens-boots-11'),
            getImage('mens-boots-12'),
            getImage('mens-boots-13'),
        ],
        description: 'Rugged and stylish Men\'s boots, built for durability and comfort. Perfect for everyday wear or your next outdoor adventure.',
        category: 'mens-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['38', '39', '40', '41', '42', '43', '44', '45'],
        colors: ['Black', 'Brown'],
    },
    {
        id: 'nba-lakers',
        name: 'NBA Lakers',
        price: 4499,
        images: [
            getImage('nba-lakers-1'),
            getImage('nba-lakers-2'),
        ],
        description: 'Show your team spirit with the NBA Lakers sneakers. These high-performance shoes feature iconic Lakers colors and branding, providing both style and comfort on and off the court.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['38', '39', '40', '41', '42', '43', '44', '45'],
        colors: ['Purple/Gold', 'White/Purple'],
    },
    {
        id: 'jordan-1-retro',
        name: 'Jordan 1',
        price: 3499,
        images: [
            getImage('jordan-1-retro-1'),
            getImage('jordan-1-retro-2'),
        ],
        description: 'The Jordan 1 brings classic court style and iconic heritage to your collection. Featuring premium materials and a timeless silhouette, these sneakers offer both comfort and exceptional style for any occasion.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['36', '37', '38', '39', '40', '41', '42', '43', '44', '45'],
        colors: ['Red/Black', 'White/Black', 'Blue'],
    },
    {
        id: 'af-custom',
        name: 'AF custom',
        price: 3499,
        images: [
            getImage('af-custom-1'),
            getImage('af-custom-2'),
        ],
        description: 'Elevate your rotation with the "AF Custom". A fresh take on an absolute classic, featuring high-quality finishes and a timeless silhouette that offers both style and durability for everyday wear.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['36', '37', '38', '39', '40', '41', '42', '43', '44', '45'],
        colors: ['White', 'Black'],
    },
    {
        id: 'runstar-motion',
        name: 'Runstar Motion',
        price: 3499,
        images: [
            getImage('runstar-motion-1'),
            getImage('runstar-motion-2'),
        ],
        description: 'Express yourself with the Runstar Motion. Its expressive, lugged outsole and premium materials offer a bold look and all-day comfort, making it a standout choice for those who want to make a statement.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['36', '37', '38', '39', '40', '41', '42', '43', '44', '45'],
        colors: ['Black', 'White'],
    },
    {
        id: 'puma-suede-xl',
        name: 'Puma Suede XL',
        price: 3499,
        images: [
            getImage('puma-suede-xl-1'),
            getImage('puma-suede-xl-2'),
        ],
        description: 'The Puma Suede XL takes the classic silhouette and adds a bold, oversized look. Featuring premium suede and a chunky design, these sneakers are perfect for making a statement with classic style and modern comfort.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['Black', 'White', 'Blue'],
    },
    {
        id: 'airforce1-valentines',
        name: 'Airforce1 Valentines',
        price: 3499,
        images: [
            getImage('af1-valentines-1'),
            getImage('af1-valentines-2'),
        ],
        description: 'Celebrate love with the special edition Airforce 1 Valentines. Featuring heart details and a classic silhouette, these sneakers are perfect for adding a touch of romance to your step.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['36', '37', '38', '39', '40'],
        colors: ['White/Red', 'Pink'],
    },
    {
        id: 'jordan-4-fear-pack',
        name: 'Jordan 4 Fear Pack',
        price: 3499,
        images: [
            getImage('jordan-4-fear-1'),
            getImage('jordan-4-fear-2'),
        ],
        description: 'The Jordan 4 Fear Pack features a sophisticated palette of black, white, and cool grey. Built with premium materials, this icon offers a timeless look and superior comfort.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['36', '37', '38', '39', '40', '41', '42', '43', '44', '45'],
        colors: ['Cool Grey', 'Black', 'White'],
    },
    {
        id: 'terrex-shoes',
        name: 'Terrex',
        price: 3499,
        images: [
            getImage('terrex-1'),
            getImage('terrex-2'),
            getImage('terrex-3'),
            getImage('terrex-4'),
        ],
        description: 'Built for the trail and the streets, these Terrex shoes offer exceptional grip and durability. Perfect for your next adventure.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['Black', 'Grey', 'Green'],
    },
    {
        id: 'converse-leather-new',
        name: 'Converse Leather',
        price: 1499,
        images: [
            getImage('converse-leather-7'),
            getImage('converse-leather-8'),
            getImage('converse-leather-9'),
            getImage('converse-leather-10'),
        ],
        description: 'Classic style meets modern comfort. These Converse leather sneakers are a versatile addition to any wardrobe, perfect for a polished yet casual look.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['36', '37', '38', '39', '40', '41', '42', '43', '44', '45'],
        colors: ['Black', 'Brown', 'Black/White', 'Pink', 'Gray', 'Cream'],
    },
    {
        id: 'new-balance-sneakers',
        name: 'New Balance',
        price: 3499,
        images: [
            getImage('new-balance-1'),
            getImage('new-balance-2'),
            getImage('new-balance-3'),
            getImage('new-balance-4'),
            getImage('new-balance-5'),
            getImage('new-balance-6'),
            getImage('new-balance-7'),
            getImage('new-balance-8'),
            getImage('new-balance-9'),
            getImage('new-balance-10'),
        ],
        description: 'Discover the perfect blend of style and comfort with these New Balance sneakers. Engineered for performance and designed for the streets, they offer a premium look and feel.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['36', '37', '38', '39', '40', '41', '42', '43', '44', '45'],
        colors: ['Black', 'White', 'Gray', 'Pink', 'Yellow'],
    },
    {
        id: 'atongmu',
        name: 'Atongmu',
        price: 1499,
        images: [
            getImage('atongmu-1'),
            getImage('atongmu-2'),
            getImage('atongmu-3'),
        ],
        description: 'Stylish and comfortable, the Atongmu sneakers are perfect for active kids. With a durable build and a fun design, they are ready for any adventure.',
        category: 'kids-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['26', '27', '28', '29', '30', '31', '32', '33', '34', '35'],
        colors: ['Black', 'Pink', 'Blue'],
    },
    {
        id: 'sport-kids',
        name: 'Sport',
        price: 1499,
        images: [
            getImage('sport-kids-1'),
            getImage('sport-kids-2'),
            getImage('sport-kids-3'),
        ],
        description: 'Get your little athlete ready for action with these sporty and comfortable shoes. Designed for performance and style, they are perfect for running, playing, and all kinds of fun activities.',
        category: 'kids-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['21', '22', '23', '24', '25', '26', '27', '28', '29', '30'],
        colors: ['Black', 'Green', 'Brown'],
    },
    {
        id: 'tick-duck',
        name: 'Tick Duck',
        price: 1499,
        images: [
            getImage('tick-duck-1'),
            getImage('tick-duck-2'),
            getImage('tick-duck-3'),
        ],
        description: 'Quack up your little one\'s style with these fun and playful "Tick Duck" shoes. Designed for comfort and durability, they are perfect for everyday adventures.',
        category: 'kids-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37'],
        colors: ['Black', 'Blue', 'Pink'],
    },
    {
        id: 'elsa-shoes',
        name: 'Elsa',
        price: 1499,
        images: [
            getImage('elsa-1'),
            getImage('elsa-2'),
        ],
        description: 'Let your little one step into a fairytale with these enchanting Elsa shoes. Perfect for fans of the frozen magic, these shoes are as comfortable as they are beautiful, featuring delightful shades of purple and pink.',
        category: 'kids-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['26', '27', '28', '29', '30', '31', '32', '33'],
        colors: ['Purple', 'Pink'],
    },
    {
        id: 'bow-girls',
        name: 'Bow Girls',
        price: 1499,
        images: [
            getImage('bow-girls-1'),
            getImage('bow-girls-2'),
        ],
        description: 'Adorable and stylish, these "Bow Girls" shoes are perfect for your little fashionista. Featuring a prominent bow for a touch of elegance, these shoes are both comfortable and chic for any occasion.',
        category: 'kids-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['26', '27', '28', '29', '30', '31', '32', '33', '34', '35'],
        colors: ['Pink', 'White'],
    },
    {
        id: 'shinny-sqmr',
        name: 'Shinny S-QMR',
        price: 1799,
        images: [
            getImage('shinny-sqmr-1'),
            getImage('shinny-sqmr-2'),
        ],
        description: 'Let your little one shine with these dazzling Shinny S-QMR sneakers. Featuring a sparkly finish and a comfortable design, they are perfect for adding a bit of glamour to any outfit.',
        category: 'kids-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37'],
        colors: ['Pink', 'Baby Pink'],
    },
    {
        id: 'kbs-kids-sneakers',
        name: 'KBS Kids Sneakers',
        price: 1499,
        images: [
            getImage('kbs-1'),
            getImage('kbs-2'),
            getImage('kbs-3'),
        ],
        description: 'Stylish and comfortable, these KBS sneakers are perfect for active kids. With a durable build and a fun design, they are ready for any adventure.',
        category: 'kids-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37'],
        colors: ['Navy Blue', 'Black', 'Pink'],
    },
    {
        id: 'fashion-bunny',
        name: 'Fashion bunny',
        price: 1499,
        images: [
            getImage('fashion-bunny-1'),
            getImage('fashion-bunny-2'),
            getImage('fashion-bunny-3'),
        ],
        description: 'Hop into style with these adorable Fashion Bunny shoes! Perfect for little feet on the go, they feature a playful design, comfortable fit, and durable construction for all-day play.',
        category: 'kids-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['26', '27', '28', '29', '30'],
        colors: ['Pink', 'White', 'Blue'],
    },
    {
        id: 'kids-airforce-1',
        name: 'Airforce 1 (Kids)',
        price: 1799,
        images: [
            getImage('kids-airforce-1-1'),
            getImage('kids-airforce-1-2'),
        ],
        description: 'A pint-sized version of the icon, the Kids\' Airforce 1 brings classic court style to the playground. It offers the same timeless comfort and durable support, ready for any adventure.',
        category: 'kids-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['26', '27', '28', '29', '30', '31', '32', '33', '34', '35'],
        colors: ['White', 'Black'],
    },
    {
        id: 'kids-sneakers-v3',
        name: 'Kids Sneakers',
        price: 1499,
        images: [
            getImage('kids-sneaker-v3-1'),
            getImage('kids-sneaker-v3-2'),
            getImage('kids-sneaker-v3-3'),
        ],
        description: 'Bright, comfy, and ready for action! These stylish kids\' sneakers are perfect for school, the park, and everything in between. Designed for durability and all-day comfort.',
        category: 'kids-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['23', '24', '25', '26', '27'],
        colors: ['Red/Black', 'Blue/White'],
    },
    {
        id: 'kids-sneakers-v2',
        name: 'Kids Sneakers',
        price: 1799,
        images: [
            getImage('kids-sneaker-v2-1'),
            getImage('kids-sneaker-v2-2'),
            getImage('kids-sneaker-v2-3'),
            getImage('kids-sneaker-v2-4'),
        ],
        description: 'Keep up with their energy with these versatile and stylish kids\' sneakers. Featuring a secure fit and a cushioned sole, they\'re built for endless fun and adventure.',
        category: 'kids-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37'],
        colors: ['Blue', 'Pink', 'Green', 'Black'],
    },
    {
        id: 'kids-sneaker-1',
        name: 'Kids Sneakers',
        price: 1799,
        images: [
            getImage('kids-sneaker-1'),
            getImage('kids-sneaker-2'),
            getImage('kids-sneaker-3'),
            getImage('kids-sneaker-4'),
        ],
        description: 'Stylish, comfortable, and built to last, these kids\' sneakers are the perfect everyday shoe for active children. The vibrant design adds a fun pop of color to any outfit.',
        category: 'kids-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['27', '28', '29', '30', '31', '32', '33', '34', '35', '36'],
        colors: ['Orange/Blue', 'Green/White'],
    },
    {
        id: 'tn-air-max-plus',
        name: 'Tn Air Max Plus',
        price: 3499,
        images: [
            getImage('tn-airmax-plus-1'),
            getImage('tn-airmax-plus-2'),
            getImage('tn-airmax-plus-3'),
            getImage('tn-airmax-plus-4'),
            getImage('tn-airmax-plus-5'),
        ],
        description: 'A striking and comfortable Tn Air Max Plus sneaker, featuring tuned Air for premium stability and cushioning. Make a bold statement with every step.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['Tiger', 'White', 'Black'],
    },
    {
        id: 'nike-metcon',
        name: 'Nike Metcon',
        price: 3499,
        images: [
            getImage('nike-metcon-1'),
            getImage('nike-metcon-2'),
            getImage('nike-metcon-3'),
        ],
        description: 'A durable and stable training shoe, the Nike Metcon is built for your toughest workouts, from weightlifting to high-intensity training. Get the support you need to crush your goals.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['37', '38', '39', '40', '41', '42', '43', '44', '45'],
        colors: ['Grey/Pink', 'Black', 'White'],
    },
    {
        id: 'nike-air-max-plus',
        name: 'Nike Air Max Plus',
        price: 3799,
        images: [
            getImage('nike-airmax-plus-1'),
            getImage('nike-airmax-plus-2'),
            getImage('nike-airmax-plus-3'),
            getImage('nike-airmax-plus-4'),
            getImage('nike-airmax-plus-5'),
        ],
        description: 'Experience legendary Tuned Air technology with the Nike Air Max Plus. Featuring a design inspired by a beach sunset, this shoe provides incredible cushioning and a striking, wavy look that\'s sure to turn heads.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['Sunset', 'Black', 'White/Blue'],
    },
    {
        id: 'jordan-3',
        name: 'Jordan 3',
        price: 3499,
        images: [
            getImage('jordan-3-1'),
            getImage('jordan-3-2'),
            getImage('jordan-3-3'),
            getImage('jordan-3-4'),
            getImage('jordan-3-5'),
            getImage('jordan-3-6'),
            getImage('jordan-3-7'),
            getImage('jordan-3-8'),
            getImage('jordan-3-9'),
        ],
        description: 'Step into a piece of history with the Air Jordan 3. Known for its visible Air unit and iconic elephant print, this sneaker is a must-have for any collector or style enthusiast, offering timeless appeal and premium comfort.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['36', '37', '38', '39', '40', '41', '42', '43', '44', '45'],
        colors: ['White Cement', 'Black Cement', 'Varsity Royal', 'Laser Orange'],
    },
    {
        id: 'airmax-97',
        name: 'Airmax 97',
        price: 3499,
        images: [
            getImage('airmax-97-1'),
            getImage('airmax-97-2'),
            getImage('airmax-97-3'),
            getImage('airmax-97-4'),
            getImage('airmax-97-5'),
        ],
        description: 'Inspired by Japanese bullet trains, the Airmax 97 features a ripple design that gives it a fast-paced look. The full-length Max Air unit provides a soft, comfortable ride, making it a stylish choice for everyday wear.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['36', '37', '38', '39', '40', '41', '42', '43', '44', '45'],
        colors: ['Silver Bullet', 'Gold', 'Black'],
    },
    {
        id: 'airmax-90',
        name: 'Airmax 90',
        price: 3499,
        images: [
            getImage('airmax-90-1'),
            getImage('airmax-90-2'),
            getImage('airmax-90-3'),
            getImage('airmax-90-4'),
            getImage('airmax-90-5'),
            getImage('airmax-90-6'),
            getImage('airmax-90-7'),
            getImage('airmax-90-8'),
            getImage('airmax-90-9'),
            getImage('airmax-90-10'),
            getImage('airmax-90-11'),
            getImage('airmax-90-12'),
        ],
        description: 'A streetwear icon, the Airmax 90 stays true to its \'90s running roots with a rubber Waffle outsole, stitched overlays, and classic TPU accents. The Max Air unit in the heel provides the comfortable cushioning you\'ve come to love.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['36', '37', '38', '39', '40', '41', '42', '43', '44', '45'],
        colors: ['Infrared', 'Volt', 'Hyper Grape', 'Triple White', 'Triple Black'],
    },
    {
        id: 'mens-official-shoes',
        name: 'Mens Official Shoes',
        price: 2999,
        images: [
            getImage('mens-official-1'),
            getImage('mens-official-2'),
            getImage('mens-official-3'),
            getImage('mens-official-4'),
            getImage('mens-official-5'),
            getImage('mens-official-6'),
            getImage('mens-official-7'),
            getImage('mens-official-8'),
            getImage('mens-official-9'),
            getImage('mens-official-10'),
        ],
        description: 'A sleek and sophisticated official shoe for the modern man. Crafted from premium leather, this shoe offers both comfort and timeless style, perfect for formal occasions or elevating your everyday look.',
        category: 'mens-shoes',
        subcategory: 'formal-shoes',
        relatedProducts: [],
        sizes: ['39', '40', '41', '42', '43', '44', '45'],
        colors: ['Black', 'Brown'],
    },
    {
        id: 'adidas-samoa',
        name: 'ADIDAS Samoa',
        price: 2800,
        images: [
            getImage('samoa-1'),
            getImage('samoa-2'),
            getImage('samoa-3'),
            getImage('samoa-4'),
            getImage('samoa-5'),
            getImage('samoa-6'),
            getImage('samoa-7'),
            getImage('samoa-8'),
            getImage('samoa-9'),
        ],
        description: 'A classic from the archives, the Adidas Samoa is a timeless trainer loved for its sleek silhouette and iconic toe bumper. A versatile choice for any casual look.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: ['nike-shox-tl-white', 'air-jordan-1-mid'],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['White/Black', 'Black/White', 'Red/White'],
    },
    {
        id: 'adidas-samba',
        name: 'Adidas Samba',
        price: 2499,
        images: [
            getImage('samba-1'),
            getImage('samba-2'),
            getImage('samba-3'),
            getImage('samba-4'),
            getImage('samba-5'),
        ],
        description: 'A true icon, the Adidas Samba is a legendary indoor football shoe that has become a streetwear staple. Its timeless design features a leather upper and suede overlays for a premium look and feel.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: ['adidas-samoa', 'converse-chuck-70-leather'],
        sizes: ['36', '37', '38', '39', '40', '41', '42', '43', '44', '45'],
        colors: ['Black/White', 'White/Black'],
    },
    {
        id: 'nike-shox-tl-white',
        name: 'Nike Shox TL - White',
        price: 3500,
        images: [
            getImage('nike-shox-1'),
            getImage('nike-shox-2'),
            getImage('nike-shox-3')
        ],
        description: 'The Nike Shox TL brings mechanical cushioning to new heights. A recrafted version of the 2003 icon, it features breathable mesh in the upper and full-length Nike Shox technology for optimal impact absorption and a bold look on the streets.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: ['nike-shox-tl-black', 'air-jordan-1-mid'],
        sizes: ['38', '39', '40', '41', '42', '43', '44', '45'],
        colors: ['White/Silver'],
    },
    {
        id: 'air-jordan-1-mid',
        name: 'Air Jordan 1 Mid',
        price: 3800,
        images: [
            getImage('jordan-1'),
            getImage('jordan-2'),
            getImage('jordan-3-image'),
            getImage('jordan-4'),
        ],
        description: 'The Air Jordan 1 Mid shoe is inspired by the first AJ1, offering fans of Jordan retros a chance to follow in the footsteps of greatness. Fresh colour trims the clean, classic materials, injecting some newness into the familiar design.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: ['nike-air-force-1-07', 'converse-chuck-70-leather'],
        sizes: ['38', '39', '40', '41', '42', '43', '44', '45'],
        colors: ['Bred Toe', 'Chicago', 'Royal Blue'],
    },
    {
        id: 'converse-chuck-70-leather',
        name: 'Converse Chuck 70 Leather',
        price: 999,
        images: [
            getImage('converse-1'),
            getImage('converse-2'),
            getImage('converse-3'),
        ],
        description: 'By 1970, the Chuck had evolved to become the pinnacle of function and utility for sport, and was considered the best basketball sneaker ever. The Chuck 70 is built off of the original 1970s design, with premium materials and an extraordinary attention to detail.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: ['polo-ralph-lauren-sneaker', 'air-jordan-1-mid'],
        sizes: ['36', '37', '38', '39', '40', '41', '42'],
        colors: ['Black', 'White'],
    },
    {
        id: 'lacoste-mens-official',
        name: 'Lacoste Men\'s Official',
        price: 2499,
        images: [
            getImage('lacoste-1'),
            getImage('lacoste-2'),
            getImage('lacoste-3'),
        ],
        description: 'A sleek and sophisticated official shoe for the modern man. Crafted from premium leather, this Lacoste shoe offers both comfort and timeless style, perfect for formal occasions or elevating your everyday look.',
        category: 'mens-shoes',
        subcategory: 'formal-shoes',
        relatedProducts: [],
        sizes: ['39', '40', '41', '42', '43', '44', '45'],
        colors: ['Black', 'Dark Brown'],
    },
    {
        id: 'nike-air-force-1-07',
        name: 'Nike Air Force 1 \'07',
        price: 3499,
        images: [
            getImage('nike-airforce-1'),
            getImage('nike-airforce-2'),
        ],
        description: 'The radiance lives on in the Nike Air Force 1 \'07, the b-ball OG that puts a fresh spin on what you know best: durably stitched overlays, clean finishes and the perfect amount of flash to make you shine.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: ['air-jordan-1-mid', 'nike-shox-tl-white'],
        sizes: ['36', '37', '38', '39', '40', '41', '42', '43', '44', '45'],
        colors: ['Triple White', 'Triple Black'],
    },
    {
        id: 'tommy-hilfiger-high-boots',
        name: 'Tommy Hilfiger High Boots',
        price: 3499,
        images: [
            getImage('tommy-boots-1'),
            getImage('tommy-boots-2'),
        ],
        description: 'Make a statement with these stunning high boots from Tommy Hilfiger. Combining classic design with modern flair, these boots are perfect for the fashion-forward woman. Ideal for both casual and dressy outfits.',
        category: 'ladies-shoes',
        subcategory: 'ladies-boots',
        relatedProducts: [],
        sizes: ['36', '37', '38', '39', '40', '41', '42'],
        colors: ['Black', 'Brown'],
    },
    {
        id: 'nike-shox-tl-black',
        name: 'Nike Shox TL - Black',
        price: 3500,
        images: [
            getImage('nike-shox-black')
        ],
        description: 'Experience the next level of cushioning with the Nike Shox TL in a sleek black colorway. Its iconic full-length Shox columns provide ultimate comfort and a standout look.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: ['nike-shox-tl-white'],
        sizes: ['38', '39', '40', '41', '42', '43', '44', '45'],
        colors: ['Triple Black'],
    },
    {
        id: 'polo-ralph-lauren-sneaker',
        name: 'Polo Ralph Lauren Sneaker',
        price: 2499,
        images: [
            getImage('polo-sneaker')
        ],
        description: 'A classic sneaker from Polo Ralph Lauren that combines preppy style with athletic comfort. A versatile shoe for any casual occasion.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: ['converse-chuck-70-leather'],
        sizes: ['38', '39', '40', '41', '42', '43'],
        colors: ['Navy', 'White', 'Black'],
    }
];

export const getProducts = () => products;
export const getProductById = (id: string) => products.find(p => p.id === id);
export const getProductsByCategory = (categoryId: string) => {
    return products.filter(p => p.category === categoryId || p.subcategory === categoryId);
}
export const getCategoryById = (id: string) => categories.find(c => c.id === id);
export const getFeaturedProducts = (limit: number = 4) => products.slice(0, limit);
export const getRelatedProducts = (product: Product) => {
    return products.filter(p => product.relatedProducts.includes(p.id) && p.id !== product.id);
}
export const getRecommendedProductsByIds = (ids: string[]) => {
  return products.filter(p => ids.includes(p.id));
}
