import type { Product, Category } from './types';
import { PlaceHolderImages } from './placeholder-images';

const getImage = (id: string) => {
  const image = PlaceHolderImages.find(img => img.id === id);
  if (image) {
    return { url: image.imageUrl, hint: image.imageHint };
  }
  return { 
    url: `https://picsum.photos/seed/${id || 'shoe'}-shoe/600/600`, 
    hint: 'shoe' 
  };
}

export const categories: Category[] = [
  { id: 'sneakers', name: 'Sneakers', parentId: null, imageUrl: getImage('samoa-new-1').url, imageHint: getImage('samoa-new-1').hint },
  { id: 'mens-shoes', name: 'Men\'s Shoes', parentId: null, imageUrl: getImage('clarks-1').url, imageHint: getImage('clarks-1').hint },
  { id: 'ladies-shoes', name: 'Ladies\' Shoes', parentId: null, imageUrl: getImage('asics-gel-1').url, imageHint: getImage('asics-gel-1').hint },
  { id: 'kids-shoes', name: 'Kids\' Shoes', parentId: null, imageUrl: getImage('kids-sneaker-v4-1').url, imageHint: getImage('kids-sneaker-v4-1').hint },
  { id: 'formal-shoes', name: 'Formal Shoes', parentId: 'mens-shoes', imageUrl: getImage('polo-loafer-1').url, imageHint: getImage('polo-loafer-1').hint },
  { id: 'ladies-boots', name: 'Boots', parentId: 'ladies-shoes', imageUrl: getImage('asics-gel-1').url, imageHint: getImage('asics-gel-1').hint },
  { id: 'soccer-boots', name: 'Soccer Boots', parentId: 'mens-shoes', imageUrl: getImage('soccer-boot-1').url, imageHint: getImage('soccer-boot-1').hint },
];

export const products: Product[] = [
    {
        id: 'nb-offer',
        name: 'New Balance Special Offer',
        price: 2999,
        images: [getImage('nb-offer-1'), getImage('nb-offer-2'), getImage('nb-offer-3')],
        description: 'OFFER OFFER! Stylish New Balance sneakers at an incredible price.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['36', '37', '38', '39', '40', '41', '42', '43', '44', '45'],
        colors: ['Multi-color'],
    },
    {
        id: 'samoa',
        name: 'Samoa',
        price: 2799,
        images: [getImage('samoa-new-1'), getImage('samoa-new-2')],
        description: 'Classic Samoa trainer loved for its sleek silhouette.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['Multi-color'],
    },
    {
        id: 'kids-open',
        name: 'Kids open',
        price: 1499,
        images: [getImage('kids-open-1'), getImage('kids-open-2'), getImage('kids-open-3'), getImage('kids-open-4')],
        description: 'Comfortable open shoes for kids.',
        category: 'kids-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36'],
        colors: ['Multi'],
    },
    {
        id: 'kids-sneakers-19-30',
        name: 'Kids sneakers',
        price: 1799,
        images: [getImage('kids-sneaker-v4-1'), getImage('kids-sneaker-v4-2'), getImage('kids-sneaker-v4-3'), getImage('kids-sneaker-v4-4'), getImage('kids-sneaker-v5-5')],
        description: 'Toddler and kids sneakers for all-day comfort.',
        category: 'kids-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30'],
        colors: ['Multi'],
    },
    {
        id: 'kids-sneakers-26-37',
        name: 'Kids sneakers',
        price: 1799,
        images: [getImage('kids-sneaker-v4-1'), getImage('kids-sneaker-v4-2'), getImage('kids-sneaker-v4-3'), getImage('kids-sneaker-v4-4')],
        description: 'Durable kids sneakers for active play.',
        category: 'kids-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37'],
        colors: ['Multi'],
    },
    {
        id: 'asics-gel',
        name: 'ASICS GEL sneakers',
        price: 2999,
        images: [getImage('asics-gel-1'), getImage('asics-gel-2')],
        description: 'ASICS GEL technology for superior cushioning and support.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['36', '37', '38', '39', '40', '41'],
        colors: ['Multi-color'],
    },
    {
        id: 'jordan-voodoo',
        name: 'Jordan Voodoo',
        price: 3499,
        images: [getImage('jordan-voodoo-1'), getImage('jordan-voodoo-2')],
        description: 'Zion Williamson x Air Jordan 1 Low OG "Voodoo" - mystical design.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['36', '37', '38', '39', '40', '41', '42', '43', '44', '45'],
        colors: ['Multi-color'],
    },
    {
        id: 'bape-star',
        name: 'Bape star',
        price: 2999,
        images: [getImage('bape-star-1'), getImage('bape-star-2'), getImage('bape-star-3')],
        description: 'A Bathing Ape classic street style.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44'],
        colors: ['Multi-color'],
    },
    {
        id: 'nike-ld-waffle',
        name: 'Nike LD waffle',
        price: 3499,
        images: [getImage('nike-ld-waffle-1')],
        description: 'Nike x sacai LDWaffle - futuristic visible tech.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['Multi-color'],
    },
    {
        id: 'nb-9060',
        name: 'New Balance 9060',
        price: 3499,
        images: [getImage('nb-9060-v2-1'), getImage('nb-9060-v2-2'), getImage('nb-9060-1'), getImage('nb-9060-2')],
        description: 'New Balance 9060 - The futuristic, visible tech aesthetic of the Y2K era.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['38', '39', '40', '41', '42', '43', '44', '45'],
        colors: ['Multi-color'],
    },
    {
        id: 'tn-air-max',
        name: 'Tn Air Max Plus',
        price: 3499,
        images: [getImage('asics-new-1')],
        description: 'Tn Air Max Plus - Iconic comfort and style.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['Black', 'Blue'],
    },
    {
        id: 'nike-air-max-plus-3799',
        name: 'Nike Air Max Plus',
        price: 3799,
        images: [getImage('asics-new-2')],
        description: 'Premium Nike Air Max Plus with superior cushioning.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['Multi'],
    },
    {
        id: 'jordan-3',
        name: 'Jordan 3',
        price: 3499,
        images: [getImage('jordan-voodoo-1')],
        description: 'Classic Jordan 3 design.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['White/Red', 'Black/Cement'],
    },
    {
        id: 'airmax-97',
        name: 'Airmax 97',
        price: 3499,
        images: [getImage('nike-ld-waffle-1')],
        description: 'Airmax 97 - Timeless silhouette.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['Silver', 'Gold'],
    },
    {
        id: 'airmax-90',
        name: 'Airmax 90',
        price: 3499,
        images: [getImage('asics-new-3')],
        description: 'Classic Airmax 90.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['Infrared', 'Laser Blue'],
    },
    {
        id: 'nike-metcon',
        name: 'Nike Metcon',
        price: 3499,
        images: [getImage('asics-new-4')],
        description: 'Durable Nike Metcon for high-intensity training.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['Grey', 'Black'],
    },
    {
        id: 'lacoste-official',
        name: 'Lacoste Men\'s Official',
        price: 2499,
        images: [getImage('clarks-1')],
        description: 'Lacoste Men\'s Official shoes for a smart look.',
        category: 'mens-shoes',
        subcategory: 'formal-shoes',
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44'],
        colors: ['Black', 'Brown'],
    },
    {
        id: 'mens-official',
        name: 'Mens Official Shoes',
        price: 2999,
        images: [getImage('clarks-2')],
        description: 'Classic official shoes for men.',
        category: 'mens-shoes',
        subcategory: 'formal-shoes',
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44'],
        colors: ['Black', 'Brown'],
    },
    {
        id: 'converse-leather',
        name: 'Converse Leather',
        price: 1499,
        images: [getImage('asics-new-5')],
        description: 'Durable Converse Leather sneakers.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['38', '39', '40', '41', '42', '43', '44'],
        colors: ['Black', 'White'],
    },
    {
        id: 'atongmu',
        name: 'Atongmu',
        price: 1499,
        images: [getImage('kids-sneaker-v4-4')],
        description: 'Atongmu stylish footwear.',
        category: 'kids-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['26', '27', '28', '29', '30'],
        colors: ['Multi'],
    },
    {
        id: 'sport-kids',
        name: 'Sport',
        price: 1499,
        images: [getImage('kids-open-1')],
        description: 'Sporty shoes for active kids.',
        category: 'kids-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['26', '27', '28', '29', '30'],
        colors: ['Multi'],
    },
    {
        id: 'tick-duck',
        name: 'Tick Duck',
        price: 1499,
        images: [getImage('kids-open-2')],
        description: 'Tick Duck kids collection.',
        category: 'kids-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['26', '27', '28', '29', '30'],
        colors: ['Multi'],
    },
    {
        id: 'elsa',
        name: 'Elsa',
        price: 1499,
        images: [getImage('kids-sneaker-v5-5')],
        description: 'Frozen themed Elsa shoes.',
        category: 'kids-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['26', '27', '28', '29', '30', '31', '32', '33'],
        colors: ['Purple', 'Pink'],
    },
    {
        id: 'bow-girls',
        name: 'Bow Girls',
        price: 1499,
        images: [getImage('kids-open-3')],
        description: 'Cute Bow Girls shoes.',
        category: 'kids-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['26', '27', '28', '29', '30', '31', '32', '33', '34', '35'],
        colors: ['Pink', 'White'],
    },
    {
        id: 'shinny-s-qmr',
        name: 'Shinny S-QMR',
        price: 1799,
        images: [getImage('kids-sneaker-v4-1')],
        description: 'Shinny S-QMR collection.',
        category: 'kids-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['26', '27', '28', '29', '30'],
        colors: ['Silver', 'Gold'],
    },
    {
        id: 'kbs-kids',
        name: 'KBS Kids Sneakers',
        price: 1499,
        images: [getImage('kids-sneaker-v4-2')],
        description: 'KBS Kids Sneakers collection.',
        category: 'kids-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['26', '27', '28', '29', '30'],
        colors: ['Multi'],
    },
    {
        id: 'fashion-bunny',
        name: 'Fashion bunny',
        price: 1499,
        images: [getImage('kids-sneaker-v4-3')],
        description: 'Fashion bunny cute shoes.',
        category: 'kids-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['26', '27', '28', '29', '30'],
        colors: ['Multi'],
    },
    {
        id: 'af1-kids',
        name: 'Airforce 1 (Kids)',
        price: 1799,
        images: [getImage('kids-sneaker-v4-4')],
        description: 'Airforce 1 for kids.',
        category: 'kids-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37'],
        colors: ['White', 'Black'],
    },
    {
        id: 'adidas-samba',
        name: 'Adidas Samba',
        price: 2499,
        images: [getImage('samoa-new-1')],
        description: 'Iconic Adidas Samba classic.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['Black/White', 'White/Black'],
    },
    {
        id: 'nike-shox-white',
        name: 'Nike Shox TL - White',
        price: 3500,
        images: [getImage('bape-star-1')],
        description: 'Nike Shox TL in Triple White.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['White'],
    },
    {
        id: 'nike-shox-black',
        name: 'Nike Shox TL - Black',
        price: 3500,
        images: [getImage('bape-star-2')],
        description: 'Nike Shox TL in Triple Black.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['Black'],
    },
    {
        id: 'air-jordan-1-mid',
        name: 'Air Jordan 1 Mid',
        price: 3800,
        images: [getImage('jordan-voodoo-2')],
        description: 'Air Jordan 1 Mid in popular colorways.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['Bred', 'Royal', 'Chicago'],
    },
    {
        id: 'converse-chuck-70',
        name: 'Converse Chuck 70 Leather',
        price: 999,
        images: [getImage('asics-new-2')],
        description: 'Chuck 70 Leather - Premium comfort.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['38', '39', '40', '41', '42', '43', '44'],
        colors: ['Black', 'Brown'],
    },
    {
        id: 'nike-af1-07',
        name: 'Nike Air Force 1 \'07',
        price: 3499,
        images: [getImage('asics-new-1')],
        description: 'Nike Air Force 1 \'07 - The classic b-ball OG.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['36', '37', '38', '39', '40', '41', '42', '43', '44', '45'],
        colors: ['Triple White', 'Triple Black'],
    },
    {
        id: 'tommy-boots',
        name: 'Tommy Hilfiger High Boots',
        price: 3499,
        images: [getImage('asics-gel-1')],
        description: 'Tommy Hilfiger High Boots - Bold style.',
        category: 'ladies-shoes',
        subcategory: 'ladies-boots',
        relatedProducts: [],
        sizes: ['36', '37', '38', '39', '40', '41', '42'],
        colors: ['Black', 'Brown'],
    },
    {
        id: 'polo-sneaker',
        name: 'Polo Ralph Lauren Sneaker',
        price: 2499,
        images: [getImage('samoa-new-1')],
        description: 'Classic Polo Ralph Lauren Sneaker.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['38', '39', '40', '41', '42', '43'],
        colors: ['Navy', 'White', 'Black'],
    },
    {
        id: 'soccer-boots',
        name: 'Soccer Boots',
        price: 3499,
        images: [getImage('soccer-boot-1'), getImage('soccer-boot-2'), getImage('soccer-boot-3'), getImage('soccer-boot-4'), getImage('soccer-boot-5'), getImage('soccer-boot-6')],
        description: 'High-performance soccer boots for professional play.',
        category: 'mens-shoes',
        subcategory: 'soccer-boots',
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['Multi'],
    }
];

export const getProducts = () => products;
export const getProductById = (id: string) => products.find(p => p.id === id);
export const getProductsByCategory = (categoryId: string) => {
    return products.filter(p => p.category === categoryId || p.subcategory === categoryId);
}
export const getCategoryById = (id: string) => categories.find(c => c.id === id);
export const getFeaturedProducts = (limit: number = 4) => products.slice(0, limit);
export const getRelatedProducts = (product: Product) => {
    return products.filter(p => product.relatedProducts.includes(p.id) && p.id !== product.id);
}
export const getRecommendedProductsByIds = (ids: string[]) => {
  return products.filter(p => ids.includes(p.id));
}
