
import type { Product, Category } from './types';
import { PlaceHolderImages } from './placeholder-images';

const getImage = (id: string) => {
  const image = PlaceHolderImages.find(img => img.id === id);
  if (image) {
    return { url: image.imageUrl, hint: image.imageHint };
  }
  // Use a seeded footwear placeholder if specific image is not found
  return { 
    url: `https://picsum.photos/seed/${id || 'shoe'}-sneaker/600/600`, 
    hint: 'footwear' 
  };
}

export const categories: Category[] = [
  { id: 'sneakers', name: 'Sneakers', parentId: null, imageUrl: getImage('samoa-new-1').url, imageHint: getImage('samoa-new-1').hint },
  { id: 'mens-shoes', name: 'Men\'s Shoes', parentId: null, imageUrl: getImage('clarks-1').url, imageHint: getImage('clarks-1').hint },
  { id: 'ladies-shoes', name: 'Ladies\' Shoes', parentId: null, imageUrl: getImage('asics-gel-1').url, imageHint: getImage('asics-gel-1').hint },
  { id: 'kids-shoes', name: 'Kids\' Shoes', parentId: null, imageUrl: getImage('kids-sneaker-v4-1').url, imageHint: getImage('kids-sneaker-v4-1').hint },
  { id: 'formal-shoes', name: 'Formal Shoes', parentId: 'mens-shoes', imageUrl: getImage('polo-loafer-1').url, imageHint: getImage('polo-loafer-1').hint },
  { id: 'ladies-boots', name: 'Boots', parentId: 'ladies-shoes', imageUrl: getImage('asics-gel-1').url, imageHint: getImage('asics-gel-1').hint },
  { id: 'soccer-boots', name: 'Soccer Boots', parentId: 'mens-shoes', imageUrl: getImage('soccer-boot-1').url, imageHint: getImage('soccer-boot-1').hint },
];

export const products: Product[] = [
    {
        id: 'samoa-offer',
        name: 'Samoa',
        price: 2999,
        images: [getImage('samoa-new-1')],
        description: 'Classic Samoa trainer loved for its sleek silhouette.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['Multi'],
    },
    {
        id: 'kids-open-offer',
        name: 'Kids open',
        price: 2799,
        images: [getImage('kids-open-1')],
        description: 'Comfortable open shoes for kids.',
        category: 'kids-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36'],
        colors: ['Multi'],
    },
    {
        id: 'kids-sneakers-1499',
        name: 'Kids Sneakers',
        price: 1499,
        images: [getImage('kids-sneaker-v4-1')],
        description: 'Stylish sneakers for kids.',
        category: 'kids-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['26', '27', '28', '29', '30'],
        colors: ['Multi'],
    },
    {
        id: 'kids-sneakers-1799',
        name: 'Kids Sneakers',
        price: 1799,
        images: [getImage('kids-sneaker-v4-2')],
        description: 'Durable sneakers for kids.',
        category: 'kids-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['26', '27', '28', '29', '30'],
        colors: ['Multi'],
    },
    {
        id: 'asics-gel-special',
        name: 'ASICS GEL sneakers',
        price: 1799,
        images: [getImage('asics-gel-1')],
        description: 'ASICS GEL technology for superior cushioning.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['36', '37', '38', '39', '40', '41'],
        colors: ['Multi'],
    },
    {
        id: 'jordan-voodoo-special',
        name: 'Jordan Voodoo',
        price: 2999,
        images: [getImage('jordan-voodoo-1')],
        description: 'Mystical Zion Williamson design.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['36', '37', '38', '39', '40', '41', '42', '43', '44', '45'],
        colors: ['Multi'],
    },
    {
        id: 'bape-star-offer',
        name: 'Bape star',
        price: 3499,
        images: [getImage('bape-star-1')],
        description: 'A Bathing Ape classic street style.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44'],
        colors: ['Multi'],
    },
    {
        id: 'nike-ld-waffle-offer',
        name: 'Nike LD waffle',
        price: 2999,
        images: [getImage('nike-ld-waffle-1')],
        description: 'Nike x sacai LDWaffle - futuristic tech.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['Multi'],
    },
    {
        id: 'nb-9060-offer',
        name: 'New Balance 9060',
        price: 3499,
        images: [getImage('nb-9060-1')],
        description: 'The futuristic, visible tech aesthetic.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['38', '39', '40', '41', '42', '43', '44', '45'],
        colors: ['Multi'],
    },
    {
        id: 'asics-offer',
        name: 'Asics',
        price: 3499,
        images: [getImage('asics-new-1')],
        description: 'Performance-driven Asics sneakers.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['Multi'],
    },
    {
        id: 'men-sandals-offer',
        name: 'Men sandals',
        price: 3499,
        images: [getImage('men-sandals-new-1')],
        description: 'Comfortable summer sandals for men.',
        category: 'mens-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44'],
        colors: ['Black', 'Brown'],
    },
    {
        id: 'soccer-boots-offer',
        name: 'Soccer boots',
        price: 1800,
        images: [getImage('soccer-boot-1')],
        description: 'Professional grade soccer boots.',
        category: 'mens-shoes',
        subcategory: 'soccer-boots',
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['Multi'],
    },
    {
        id: 'clarks-offer',
        name: 'Clarks',
        price: 3999,
        images: [getImage('clarks-1')],
        description: 'Timeless Clarks comfort and quality.',
        category: 'mens-shoes',
        subcategory: 'formal-shoes',
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['Brown', 'Black'],
    },
    {
        id: 'nike-shocks-offer',
        name: 'Nike shocks',
        price: 2999,
        images: [getImage('asics-new-4')],
        description: 'Classic Nike Shox styling and support.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['White', 'Black'],
    },
    {
        id: 'polo-loafer-offer',
        name: 'Polo loafer',
        price: 3999,
        images: [getImage('polo-loafer-1')],
        description: 'Elegant Polo Ralph Lauren loafers.',
        category: 'mens-shoes',
        subcategory: 'formal-shoes',
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44'],
        colors: ['Tan', 'Black'],
    },
    {
        id: 'samba-double-sole-offer',
        name: 'Samba double sole',
        price: 2499,
        images: [getImage('samoa-new-1')],
        description: 'Adidas Samba with a modern double sole.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44'],
        colors: ['Multi'],
    },
    {
        id: 'mcqueen-offer',
        name: 'Alexander McQueen',
        price: 2999,
        images: [getImage('asics-new-2')],
        description: 'Luxury designer sneakers.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['38', '39', '40', '41', '42', '43', '44'],
        colors: ['White', 'Black'],
    },
    {
        id: 'timberland-offer',
        name: 'Casual Timberland',
        price: 3499,
        images: [getImage('clarks-4')],
        description: 'Durable and casual Timberland style.',
        category: 'mens-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['Wheat', 'Black'],
    },
    {
        id: 'naked-wolf-offer',
        name: 'Naked wolf',
        price: 2800,
        images: [getImage('asics-gel-1')],
        description: 'Bold Naked Wolf fashion sneakers.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['36', '37', '38', '39', '40', '41'],
        colors: ['Multi'],
    },
    {
        id: 'vans-offer',
        name: 'Vans',
        price: 3499,
        images: [getImage('asics-new-5')],
        description: 'Classic Vans Off The Wall sneakers.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['38', '39', '40', '41', '42', '43', '44'],
        colors: ['Multi'],
    },
    {
        id: 'new-amiri-offer',
        name: 'New Amiri',
        price: 1499,
        images: [getImage('jordan-voodoo-2')],
        description: 'Premium designer Amiri sneakers.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44'],
        colors: ['Multi'],
    },
    {
        id: 'nb-550-offer',
        name: 'New balance 550',
        price: 3499,
        images: [getImage('nb-offer-1')],
        description: 'New Balance 550 retro basketball style.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['38', '39', '40', '41', '42', '43', '44', '45'],
        colors: ['Multi'],
    },
    {
        id: 'mens-boots-offer',
        name: 'Men\'s Boots',
        price: 3499,
        images: [getImage('clarks-1')],
        description: 'Rugged and stylish boots for men.',
        category: 'mens-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['Brown', 'Black'],
    },
    {
        id: 'nba-lakers-offer',
        name: 'NBA Lakers',
        price: 4800,
        images: [getImage('jordan-voodoo-1')],
        description: 'Lakers themed basketball shoes.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['Purple/Gold'],
    },
    {
        id: 'jordan-1-offer',
        name: 'Jordan 1',
        price: 4499,
        images: [getImage('jordan-voodoo-2')],
        description: 'Iconic Air Jordan 1.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['Multi'],
    },
    {
        id: 'af-custom-offer',
        name: 'AF custom',
        price: 3499,
        images: [getImage('asics-new-1')],
        description: 'Customized Air Force 1.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['36', '37', '38', '39', '40', '41', '42', '43', '44', '45'],
        colors: ['Multi'],
    },
    {
        id: 'runstar-motion-offer',
        name: 'Runstar Motion',
        price: 3499,
        images: [getImage('asics-new-2')],
        description: 'Converse Runstar Motion wavy platform.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['38', '39', '40', '41', '42', '43', '44'],
        colors: ['Multi'],
    },
    {
        id: 'puma-suede-xl-offer',
        name: 'Puma Suede XL',
        price: 3499,
        images: [getImage('samoa-new-2')],
        description: 'Classic Puma Suede with XL silhouette.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44'],
        colors: ['Multi'],
    },
    {
        id: 'af1-valentines-offer',
        name: 'Airforce1 Valentines',
        price: 3499,
        images: [getImage('asics-new-3')],
        description: 'Limited edition Valentines Day Air Force 1.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['36', '37', '38', '39', '40', '41'],
        colors: ['Red/White'],
    },
    {
        id: 'jordan-4-fear-offer',
        name: 'Jordan 4 Fear Pack',
        price: 3499,
        images: [getImage('jordan-voodoo-1')],
        description: 'Jordan 4 Fear Pack collection.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['Black/Grey'],
    },
    {
        id: 'terrex-offer',
        name: 'Terrex',
        price: 3499,
        images: [getImage('asics-new-4')],
        description: 'Adidas Terrex outdoor adventure shoes.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['Multi'],
    },
    {
        id: 'converse-leather-offer',
        name: 'Converse Leather',
        price: 3499,
        images: [getImage('asics-new-5')],
        description: 'Durable Converse Leather sneakers.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['38', '39', '40', '41', '42', '43', '44'],
        colors: ['Black', 'White'],
    },
    {
        id: 'new-balance-general',
        name: 'New Balance',
        price: 1499,
        images: [getImage('nb-9060-1')],
        description: 'Classic New Balance comfort.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['Grey'],
    },
    {
        id: 'atongmu-kids',
        name: 'Atongmu',
        price: 3499,
        images: [getImage('kids-sneaker-v4-4')],
        description: 'Atongmu stylish footwear for kids.',
        category: 'kids-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['26', '27', '28', '29', '30'],
        colors: ['Multi'],
    },
    {
        id: 'sport-kids-shoe',
        name: 'Sport',
        price: 1499,
        images: [getImage('kids-open-1')],
        description: 'Sporty shoes for active kids.',
        category: 'kids-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['26', '27', '28', '29', '30'],
        colors: ['Multi'],
    },
    {
        id: 'tick-duck-kids',
        name: 'Tick Duck',
        price: 1499,
        images: [getImage('kids-open-2')],
        description: 'Tick Duck fun kids collection.',
        category: 'kids-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['26', '27', '28', '29', '30'],
        colors: ['Multi'],
    },
    {
        id: 'elsa-kids',
        name: 'Elsa',
        price: 1499,
        images: [getImage('kids-sneaker-v5-5')],
        description: 'Frozen themed Elsa shoes for girls.',
        category: 'kids-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['26', '27', '28', '29', '30', '31', '32', '33'],
        colors: ['Purple', 'Pink'],
    },
    {
        id: 'bow-girls-shoe',
        name: 'Bow Girls',
        price: 1499,
        images: [getImage('kids-open-3')],
        description: 'Cute Bow Girls shoes.',
        category: 'kids-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['26', '27', '28', '29', '30', '31', '32', '33', '34', '35'],
        colors: ['Pink', 'White'],
    },
    {
        id: 'shinny-s-qmr-kids',
        name: 'Shinny S-QMR',
        price: 1499,
        images: [getImage('kids-sneaker-v4-1')],
        description: 'Shinny sparkly collection.',
        category: 'kids-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['26', '27', '28', '29', '30'],
        colors: ['Silver', 'Gold'],
    },
    {
        id: 'kbs-kids-sneaker-offer',
        name: 'KBS Kids Sneakers',
        price: 1799,
        images: [getImage('kids-sneaker-v4-2')],
        description: 'KBS Kids Sneakers for everyday wear.',
        category: 'kids-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['26', '27', '28', '29', '30'],
        colors: ['Multi'],
    },
    {
        id: 'fashion-bunny-kids',
        name: 'Fashion bunny',
        price: 1499,
        images: [getImage('kids-sneaker-v4-3')],
        description: 'Fashion bunny cute shoes.',
        category: 'kids-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['26', '27', '28', '29', '30'],
        colors: ['Multi'],
    },
    {
        id: 'af1-kids-offer',
        name: 'Airforce 1 (Kids)',
        price: 1499,
        images: [getImage('kids-sneaker-v4-4')],
        description: 'Airforce 1 icon for kids.',
        category: 'kids-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36', '37'],
        colors: ['White', 'Black'],
    },
    {
        id: 'kids-sneakers-v3',
        name: 'Kids Sneakers',
        price: 1799,
        images: [getImage('kids-sneaker-v4-1')],
        description: 'Comfortable kids sneakers.',
        category: 'kids-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['26', '27', '28', '29', '30'],
        colors: ['Multi'],
    },
    {
        id: 'kids-sneakers-v4',
        name: 'Kids Sneakers',
        price: 1499,
        images: [getImage('kids-sneaker-v4-2')],
        description: 'Durable kids sneakers.',
        category: 'kids-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['26', '27', '28', '29', '30'],
        colors: ['Multi'],
    },
    {
        id: 'kids-sneakers-v5',
        name: 'Kids Sneakers',
        price: 1799,
        images: [getImage('kids-sneaker-v4-3')],
        description: 'Modern kids sneakers.',
        category: 'kids-shoes',
        subcategory: null,
        relatedProducts: [],
        sizes: ['26', '27', '28', '29', '30'],
        colors: ['Multi'],
    },
    {
        id: 'tn-air-max-plus-offer',
        name: 'Tn Air Max Plus',
        price: 1799,
        images: [getImage('asics-new-1')],
        description: 'Tn Air Max Plus iconic comfort.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['Black', 'Blue'],
    },
    {
        id: 'nike-metcon-offer',
        name: 'Nike Metcon',
        price: 3499,
        images: [getImage('asics-new-4')],
        description: 'Durable Nike Metcon.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['Grey', 'Black'],
    },
    {
        id: 'nike-air-max-plus-special',
        name: 'Nike Air Max Plus',
        price: 3499,
        images: [getImage('asics-new-2')],
        description: 'Striking Nike Air Max Plus design.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['Multi'],
    },
    {
        id: 'jordan-3-offer',
        name: 'Jordan 3',
        price: 3799,
        images: [getImage('jordan-voodoo-1')],
        description: 'Classic Jordan 3 with elephant print.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['White/Red', 'Black/Cement'],
    },
    {
        id: 'airmax-97-offer',
        name: 'Airmax 97',
        price: 3499,
        images: [getImage('nike-ld-waffle-1')],
        description: 'Airmax 97 ripple design.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['Silver', 'Gold'],
    },
    {
        id: 'airmax-90-offer',
        name: 'Airmax 90',
        price: 3499,
        images: [getImage('asics-new-3')],
        description: 'Classic Airmax 90 comfort.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['Infrared', 'Laser Blue'],
    },
    {
        id: 'mens-official-shoe-offer',
        name: 'Mens Official Shoes',
        price: 3499,
        images: [getImage('clarks-2')],
        description: 'Sharp official shoes.',
        category: 'mens-shoes',
        subcategory: 'formal-shoes',
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44'],
        colors: ['Black', 'Brown'],
    },
    {
        id: 'adidas-samoa-offer',
        name: 'ADIDAS Samoa',
        price: 2999,
        images: [getImage('samoa-new-1')],
        description: 'Premium Adidas Samoa.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['Multi'],
    },
    {
        id: 'adidas-samba-offer',
        name: 'Adidas Samba',
        price: 2800,
        images: [getImage('samoa-new-1')],
        description: 'Streetwear legend Adidas Samba.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['Black/White', 'White/Black'],
    },
    {
        id: 'nike-shox-tl-white-offer',
        name: 'Nike Shox TL - White',
        price: 2499,
        images: [getImage('bape-star-1')],
        description: 'Nike Shox TL Triple White.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['White'],
    },
    {
        id: 'air-jordan-1-mid-offer',
        name: 'Air Jordan 1 Mid',
        price: 3500,
        images: [getImage('jordan-voodoo-2')],
        description: 'Versatile Air Jordan 1 Mid.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['Bred', 'Royal', 'Chicago'],
    },
    {
        id: 'converse-chuck-70-leather-offer',
        name: 'Converse Chuck 70 Leather',
        price: 3800,
        images: [getImage('asics-new-2')],
        description: 'Premium leather Converse.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['38', '39', '40', '41', '42', '43', '44'],
        colors: ['Black', 'Brown'],
    },
    {
        id: 'lacoste-official-offer',
        name: 'Lacoste Men\'s Official',
        price: 999,
        images: [getImage('clarks-1')],
        description: 'Lacoste refined official shoes.',
        category: 'mens-shoes',
        subcategory: 'formal-shoes',
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44'],
        colors: ['Black', 'Brown'],
    },
    {
        id: 'nike-af1-07-offer',
        name: 'Nike Air Force 1 \'07',
        price: 2499,
        images: [getImage('asics-new-1')],
        description: 'The basketball OG.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['36', '37', '38', '39', '40', '41', '42', '43', '44', '45'],
        colors: ['Triple White', 'Triple Black'],
    },
    {
        id: 'tommy-boots-offer',
        name: 'Tommy Hilfiger High Boots',
        price: 3499,
        images: [getImage('asics-gel-1')],
        description: 'Tommy Hilfiger high boots.',
        category: 'ladies-shoes',
        subcategory: 'ladies-boots',
        relatedProducts: [],
        sizes: ['36', '37', '38', '39', '40', '41', '42'],
        colors: ['Black', 'Brown'],
    },
    {
        id: 'nike-shox-tl-black-offer',
        name: 'Nike Shox TL - Black',
        price: 3499,
        images: [getImage('bape-star-2')],
        description: 'Nike Shox TL Triple Black.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['40', '41', '42', '43', '44', '45'],
        colors: ['Black'],
    },
    {
        id: 'polo-sneaker-offer',
        name: 'Polo Ralph Lauren Sneaker',
        price: 3500,
        images: [getImage('samoa-new-1')],
        description: 'Classic Polo heritage sneakers.',
        category: 'sneakers',
        subcategory: null,
        relatedProducts: [],
        sizes: ['38', '39', '40', '41', '42', '43'],
        colors: ['Navy', 'White', 'Black'],
    }
];

export const getProducts = () => products;
export const getProductById = (id: string) => products.find(p => p.id === id);
export const getProductsByCategory = (categoryId: string) => {
    return products.filter(p => p.category === categoryId || p.subcategory === categoryId);
}
export const getCategoryById = (id: string) => categories.find(c => c.id === id);
export const getFeaturedProducts = (limit: number = 4) => products.slice(0, limit);
export const getRelatedProducts = (product: Product) => {
    return products.filter(p => product.relatedProducts.includes(p.id) && p.id !== product.id);
}
export const getRecommendedProductsByIds = (ids: string[]) => {
  return products.filter(p => ids.includes(p.id));
}
